import { useState } from "react";

function Dashboard() {
  const [resume, setResume] = useState("");
  const [job, setJob] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);

  const handleAnalyze = () => {
    if (loading) return;

    setLoading(true);
    setResult(null);

    setTimeout(() => {
      setResult({
        score: 86,
        missingSkills: ["Docker", "TypeScript"],
        improvedResume: "Improved resume content goes here...",
        coverLetter: "Cover letter generated by AI..."
      });

      setLoading(false);
    }, 2000);
  };

  return (
    <div className="min-h-screen flex bg-gray-950 text-white">

      
      <div className="w-64 bg-gray-900 border-r border-gray-800 p-5">
        <h1 className="text-xl font-bold text-blue-500 mb-8">
          JobAI
        </h1>

        <ul className="space-y-4 text-gray-300">
          <li className="hover:text-white cursor-pointer">Dashboard</li>
          <li className="hover:text-white cursor-pointer">Analyze</li>
          <li className="hover:text-white cursor-pointer">History</li>
          <li className="hover:text-white cursor-pointer">Insights</li>
        </ul>
      </div>

  
      <div className="flex-1 p-8">

      
        <h2 className="text-3xl font-bold mb-6">
          AI Resume Analyzer
        </h2>

      
        <div className="grid grid-cols-2 gap-6">

          <textarea
            className="h-60 p-4 bg-gray-900 border border-gray-700 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Paste your resume..."
            value={resume}
            onChange={(e) => setResume(e.target.value)}
          />

          <textarea
            className="h-60 p-4 bg-gray-900 border border-gray-700 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Paste job description..."
            value={job}
            onChange={(e) => setJob(e.target.value)}
          />
        </div>

      
        <button
          onClick={handleAnalyze}
          className="mt-6 px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg font-semibold"
        >
          {loading ? "Analyzing..." : "Analyze Resume"}
        </button>

    
        {loading ? (
          <div className="mt-10 flex flex-col items-center text-center">

            <div className="w-10 h-10 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>

            <h2 className="mt-4 text-lg font-semibold text-blue-400">
              Analyzing Resume...
            </h2>

            <p className="text-gray-500 text-sm mt-1">
              AI is processing your resume and job match
            </p>

          </div>
        ) : result ? (
          <div className="mt-10 space-y-6">

      
            <div className="bg-gray-900 p-5 rounded-xl border border-gray-800">
              <h3 className="text-green-400 text-xl font-bold">
                Match Score: {result.score}%
              </h3>
            </div>


            <div className="bg-gray-900 p-5 rounded-xl border border-gray-800">
              <h3 className="font-semibold mb-2">Missing Skills</h3>
              <p className="text-gray-400">
                {result.missingSkills.join(", ")}
              </p>
            </div>

            
            <div className="bg-gray-900 p-5 rounded-xl border border-gray-800">
              <h3 className="font-semibold mb-2">Improved Resume</h3>
              <p className="text-gray-400">{result.improvedResume}</p>
            </div>

      
            <div className="bg-gray-900 p-5 rounded-xl border border-gray-800">
              <h3 className="font-semibold mb-2">Cover Letter</h3>
              <p className="text-gray-400">{result.coverLetter}</p>
            </div>

          </div>
        ) : null}

      </div>
    </div>
  );
}

export default Dashboard;

